### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by inz5o2** [danny-burrows/rotate-screen#12]
When importing the module i get the following error message with Python 3.9.13 :

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\rotatescreen\__init__.py", line 1, in <module>
    from .display import *
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\rotatescreen\display.py", line 77, in <module>
    def get_primary_display() -> Display | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
python-BaseException

Process finished with exit code 1
```

The solution is to change the 
`def get_primary_display() -> Display | None:` 
to 
`def get_primary_display() -> "Display | None":`
in the source code of display.py

I don't know if somebody else had this issue as well. It can be just a problem with this specific Python version

After changing it i could import the module and run the test code without any error.

I hope this helps.

**Comment by danny-burrows** [comment]
Thanks for submitting the issue! I'm pushing a fix now
